### ISSUE TITLE
OpenOCD-Nuvoton doesn't work on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by kristofmulier** [OpenNuvoton/OpenOCD-Nuvoton#12]
<h2>1. The problem explained</h2>

Generally, I use the following command to launch OpenOCD:

```sh
$ openocd -f openocd_probe.cfg -f openocd_chip.cfg -c "init; reset halt"
```
For the `NuTiny NUC029SDE V1.0` board, the config files look like this:

```
# openocd_probe.cfg
# =================
# OpenOCD probe config file for NULINK_ME_V3_0
# Must be applied before the chip config file!
source [find interface/nulink.cfg]
transport select hla_swd
```
```
# openocd_chip.cfg
# ================
# OpenOCD chip config file for NUC029SDE
source [find target/numicroM0.cfg]
reset_config srst_only
```

On Windows this works just fine. On Ubuntu 20.04.1 it fails:

```sh
$ openocd -f openocd_probe.cfg -f openocd_chip.cfg -c "init; reset halt"

Open On-Chip Debugger 0.10.0-dev-00459-gb251c4cf (2020-09-14-10:20)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
../config/openocd_probe.cfg:4: Error: Can't find interface/nulink.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 60
at file "../config/openocd_probe.cfg", line 4
```

<h2>2. Some context</h2>

I'm part of the startup **Embeetle IDE**. We build a new free IDE for microntrollers (see https://embeetle.com). Our IDE supports a lot of Nuvoton boards, and they all work in Windows:

- `numaker_m031sd v1.2`
- `numaker_m031se v1.1`
- `numaker_m031tb v1.1`
- `numaker_m031tc v1.1`
- `numaker_m032se v1.3`
- `numaker_m263ki v1.2`
- `numaker_m483kg v1.1`
- `nutiny_nuc029sde v1.0`

I've tested some of them in Ubuntu (not a virtual machine, but native Ubuntu) and they all fail with the same error message:

```
Error: Can't find interface/nulink.cfg
```

Please help.

Kind regards,
Kristof Mulier

**Comment by ZaleYu** [comment]
Hi Mulier:
It seemed that your OpenOCD was not the Nuvoton-customized one.
Could you download NuEclipse of Linux version:
https://www.nuvoton.com/tool-and-software/software-development-tool/driver/

Then extract the Nuvoton-customized OpenOCD including the bin and scripts folder and try again?
Launch NuElipse and use the New Project Wizard to create a M031 project to download and debug it.
Please refer to the section 3.2 of user manual if you are not familiar with NuEclipse.

Sincerely, 
Zale Yu

**Comment by kristofmulier** [comment]
Hi Mr. Yu,
Thank you for your quick response :-)
I did use the Nuvoton-customized OpenOCD. In fact, I pulled this GitHub repo and then built it for both Windows and Linux. The way I did that is explained in this issue:
https://github.com/OpenNuvoton/OpenOCD-Nuvoton/issues/10

Thank you very much for your help.

Kind regards,
Kristof Mulier

**Comment by ZaleYu** [comment]
Hi Mulier:
Could you provide your openocd_probe.cfg for debugging?

Sincerely,
Zale Yu

**Comment by kristofmulier** [comment]
Hi Mr. Yu,
This is my `openocd_probe.cfg`:

```
# openocd_probe.cfg
# =================
# OpenOCD probe config file for NULINK_ME_V3_0
# Must be applied before the chip config file!
source [find interface/nulink.cfg]
transport select hla_swd
```

And this is my `openocd_chip.cfg`:

```
# openocd_chip.cfg
# ================
# OpenOCD chip config file for NUC029SDE
source [find target/numicroM0.cfg]
reset_config srst_only
```

It works on Windows, not on Linux. The OpenOCD versions I use on Windows and Linux are both the result from applying the build scripts from Liviu Ionescu, as explained on this page:

https://github.com/OpenNuvoton/OpenOCD-Nuvoton/issues/10

Thank you very much for your help 👍 

Kind regards,
Kristof Mulier

**Comment by ZaleYu** [comment]
Hi Mulier:
It seemed that OpenOCD failed to find the nulink.cfg file. Maybe you can try the following command relative to the current openocd directory:

openocd -s ../tcl -f interface/nulink.cfg -f target/numicroM0.cfg

Here I assume that your openocd executable is located in openocd/src. If not, please modify the path after the -s command to locate the tcl directory.

Sincerely, 
Zale Yu

**Comment by kristofmulier** [comment]
Hi Mr. Zale,
Thank you very much for your reply. I tried the following command, and it works:

```sh
$ /home/.../openocd_nuvoton/bin/openocd -s /home/.../openocd_nuvoton/scripts -f openocd_probe.cfg -f openocd_chip.cfg -c "init; reset halt"
```
In this command, you can see the following paths:
- `/home/.../openocd_nuvoton/`: full path to the Nuvoton OpenOCD installation.
- `/home/.../openocd_nuvoton/bin/openocd`: full path to the Nuvoton OpenOCD executable.
- `/home/.../openocd_nuvoton/scripts/`: full path to the Nuvoton OpenOCD `scripts` folder (which is obviously part of the OpenOCD installation).

(the three dots are just a replacement for a very long path for visual reasons)

The only difference with my previous command, is that I pass the full path to the OpenOCD scripts folder with the `-s` flag. Fortunately, this is not necessary for the Windows version of the Nuvoton OpenOCD. Is it possible to change something in the source code such that I don't need to pass this `-s` flag for the Linux version either?

That would significantly simplify the Nuvoton board support in Embeetle IDE (for Linux).

Thank you very much :+1: 

Kind regards,
Kristof Mulier

**Comment by ZaleYu** [comment]
Hi Mulier:
According to https://github.com/OpenNuvoton/OpenOCD-Nuvoton/blob/master/src/helper/options.c (line 157), OpenOCD concatenates run_prefix, PKGDATADIR and /scripts into one string and adds it into the search string of tcl folder. You can use the command with -d 3 to see these strings (run_prefix, PKGDATADIR) in the very beginning of the openocd debug log. 

If the search string of tcl folder can locate your tcl folder correctly, the -s command is needless. If not, you can assign PKGDATADIR when building openocd. Maybe you can observe them in your case to see what to do in the next step.

Sincerely,
Zale Yu

**Comment by kristofmulier** [comment]
Hi Mr. Zale,
Thank you very much for your quick reply. I just ran OpenOCD with the `-d 3` flag as you suggested:

```sh
$ openocd -f openocd_probe.cfg -f openocd_chip.cfg -c "init; reset halt" -d 3

Open On-Chip Debugger 0.10.0-dev-00459-gb251c4cf (2020-09-14-10:20)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
User : 13 1 command.c:544 command_print(): debug_level: 3
Debug: 14 1 options.c:102 add_default_dirs(): bindir=bin
Debug: 15 1 options.c:103 add_default_dirs(): pkgdatadir=
Debug: 16 1 options.c:104 add_default_dirs(): run_prefix=
Debug: 17 1 configuration.c:42 add_script_search_dir(): adding /root/.openocd
Debug: 18 1 configuration.c:42 add_script_search_dir(): adding /site
Debug: 19 1 configuration.c:42 add_script_search_dir(): adding /scripts
Debug: 20 1 configuration.c:82 find_file(): found ../config/openocd_probe.cfg
User : 21 2 command.c:687 command_run_line(): ../config/openocd_probe.cfg:4: Error: Can't find interface/nulink.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 60
at file "../config/openocd_probe.cfg", line 4
```
It looks like `pkgdatadir` and `run_prefix` are empty.

You said:
> "you can assign `PKGDATADIR` when building openocd."

How exactly should I do that? I use the build scripts from Liviu Ionescu (as explained in this post: https://github.com/OpenNuvoton/OpenOCD-Nuvoton/issues/10), but I don't know how to modify these scripts. I merely know how to use them.

Thank you very much for your help.

Kind regards,
Kristof Mulier

**Comment by ZaleYu** [comment]
Hi Mulier:
I committed a change to fix this issue. Please try it again.

Sincerely, 
Zale Yu

**Comment by kristofmulier** [comment]
Hi Mr. Zale,
Thank you very much. Unfortunately, your latest fix caused some errors in the build for the Windows executables. When running the build scripts from Liviu Ionescu (which used to work perfectly before) with the `--all` flag, I should get executables for:

- Windows 64bit
- Windows 32bit
- Linux 64bit
- Linux 32bit

Unfortunately, the Windows executables are missing from the output folder `~/Work/openocd-0.10.0-15/deploy`. It looks like the build for Windows fails. This is how the build output in my console ends:

```sh
libtool: link: x86_64-w64-mingw32-gcc -ffunction-sections -fdata-sections -pipe -m64 -O2 -w -D__USE_MINGW_ANSI_STDIO -Wall -Wstrict-prototypes -Wformat-security -Wshadow -O2 -Wl,--gc-sections -o openocd.exe main.o  -L/Host/home/kristof/Work/openocd-0.10.0-15/win32-x64/install/libs/lib ./.libs/libopenocd.a -lws2_32 -lhid -lsetupapi -lusb /Host/home/kristof/Work/openocd-0.10.0-15/win32-x64/install/libs/lib/libusb-1.0.dll.a ../jimtcl/libjim.a -L/Host/home/kristof/Work/openocd-0.10.0-15/win32-x64/install/libs/lib -L/Host/home/kristof/Work/openocd-0.10.0-15/win32-x64/install/libs/lib
/opt/xbb/usr/lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld: ./.libs/libopenocd.a(libhelper_la-options.o):options.c:(.text$parse_cmdline_args+0x466): undefined reference to `realpath'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:560: openocd.exe] Error 1
make[4]: Leaving directory '/tmp/win32-x64/build/openocd/src'
make[3]: *** [Makefile:629: all-recursive] Error 1
make[3]: Leaving directory '/tmp/win32-x64/build/openocd/src'
make[2]: *** [Makefile:460: all] Error 2
make[2]: Leaving directory '/tmp/win32-x64/build/openocd/src'
make[1]: *** [Makefile:514: all-recursive] Error 1
make[1]: Leaving directory '/tmp/win32-x64/build/openocd'
make: *** [Makefile:422: all] Error 2
```
I have saved the complete build output to a file, and added it here to this post (see `build_output.txt`). I hope it helps to trace down the error:

[build_output.txt](https://github.com/OpenNuvoton/OpenOCD-Nuvoton/files/5501853/build_output.txt)

For your convenience, I'll repeat here how exactly I build OpenOCD with the build scripts from Liviu Ionescu:

-----------------------------------------

<h3>1 Install docker</h3>

I issue these commands to install docker:

    $ sudo apt-get clean
    $ sudo apt-get update
    $ sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    $ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    $ version_name=$(lsb_release -cs)
    $ sudo add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu  ${version_name} stable"
    $ sudo apt-get update
    $ sudo apt-get -y install docker-ce

To check if docker is properly installed, I run: 

    $ sudo docker run hello-world

To configure docker as regular user:

    $ sudo groupadd docker
    $ sudo gpasswd -a ${USER} docker
    $ sudo service docker restart
    $ shutdown -r now

The last command reboots Linux. Now Docker should work without sudo command. To test, run: 

    $ docker run hello-world

<h3>2 Download build scripts</h3>

First I cleanup anything left from a previous build:

    $ sudo rm -rf ~/Downloads/openocd-xpack.git
    $ sudo rm -rf ~/Work

Now I download the build scripts from Liviu Ionescu:

    $ git clone --recurse-submodules https://github.com/xpack-dev-tools/openocd-xpack.git ~/Downloads/openocd-xpack.git

His build scripts need a slight edit, such that the Nuvoton fork is pulled instead of the regular OpenOCD:

    $ cd ~/Downloads/openocd-xpack.git/scripts/
    $ gedit defs-source.sh

The last three lines in `defs-source.sh` should be uncommented and changed into:

    OPENOCD_GIT_URL=https://github.com/OpenNuvoton/OpenOCD-Nuvoton.git
    OPENOCD_GIT_BRANCH=master
    OPENOCD_GIT_COMMIT=HEAD

The build scripts are ready now.

<h3>3 Start build</h3>

To do the build, just issue the command:

    $ bash ~/Downloads/openocd-xpack.git/scripts/build.sh --all

Eventually you will find the build output in `~/Work/openocd-0.10.0-15/deploy`. The beauty of this procedure is that it generates builds for Windows 32b, Windows 64b, Linux 32b and Linux 64b!

**Comment by ZaleYu** [comment]
Hi Mulier:
I fixed this issue and successfully built OpenOCD on Linux and Windows. Please try it again.

Sincerely,
Zale Yu

**Comment by kristofmulier** [comment]
Hi Mr. Zale,
Thank you very much for fixing this issue. I can confirm that Nuvoton OpenOCD now builds successfully for Windows and Linux, and it works properly on `Ubuntu 20.04.1`.

I will add the new OpenOCD build to the next Embeetle IDE release, which will probably be launched tomorrow.

Kind regards,
Kristof Mulier

**Comment by jz13138** [comment]
Hi Everyone,
I face some problems with Nuvoton OpenOCD on `Ubuntu 22.04.4`.

The BSY Led on the Nu-Link-debugger lights up shortly.
The debugging terminates immediately without further notification.
The 

Console looks like this: 
```
<terminated>...GDB Nuvoton Nu-Link Debugging] openocd_8051_1T:
Open On-Chip Debugger 0.10.0-dev (2023-07-06-07:19)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 1 kHz
Info : NULINK is Nu-Link1
Info : NULINK firmware_version(7623), product_id(0x30012009)
Info : IDCODE: 0x00DA3650
Info : IDCODE: 0x00DA3650
Started by GNU ARM Eclipse
```

openocd_8051_1T does not show any problems:
```
${openocd_nulink_path}/openocd_8051_1T -f ../scripts/interface/nulink.cfg -f ../scripts/target/numicro8051_1T.cfg -c "init; reset halt"
Open On-Chip Debugger 0.10.0-dev (2023-07-06-07:19)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 1 kHz
Info : NULINK is Nu-Link1
Info : NULINK firmware_version(7623), product_id(0x30012009)
Info : IDCODE: 0x00DA3650
Info : IDCODE: 0x00DA3650
NuMicro.cpu: target state: halted
target halted due to debug-request, pc: 0x00000000
```
The long version with -d 3 is attached.
[OpenOcd_d3_out.txt](https://github.com/OpenNuvoton/OpenOCD-Nuvoton/files/14875402/OpenOcd_d3.txt)

The same setup seems to work on Windows.

Help would be appreciated to get the linux-version running.

Kind regards,
jz13138
