### ISSUE TITLE
Upstream to `openocd`?

### ISSUE THREAD

**Issue by travisby** [OpenNuvoton/OpenOCD-Nuvoton#13]
Hello,

I am using a NuMaker-PFM-M2351 and trying to integrate it with some IDEs.  

It'd be really helpful if the nulink-usb interface and m2351 targets were upstreamed!  

I can usually make the tools work with the special version of openocd here, but it became problematic when trying to hook into platformio.  It'd make it a lot easier if it were regular openocd!

**Comment by ZaleYu** [comment]
Hi travisby:
We have tried to push [our patch](http://openocd.zylin.com/#/c/5646/) into the upstream of OpenOCD. The patch was viewed for a long time. As long as it is accepted, we will push a new patch which supports M2351.

Sincerely, 
Zale Yu

**Comment by travisby** [comment]
Thanks @ZaleYu !  I didn't realize there was already a patch in process.
