### ISSUE TITLE
Possibly typo

### ISSUE THREAD

**Issue by burrbull** [OpenNuvoton/OpenOCD-Nuvoton#15]
https://github.com/OpenNuvoton/OpenOCD-Nuvoton/blob/cc54018c72f7e85fa8702974fc27913e4746af6d/src/jtag/drivers/nulink_usb.c#L54

Maybe
```C
#define V7M_MAX_COMMAND_LENGTH (NULINK2_HID_MAX_SIZE - 3) 
```
should be here?

**Comment by ZaleYu** [comment]
Hi burrbull:
Thanks for your reminding me of the potential issue. I am going to fix it.

Sincerely,
Zale Yu

**Comment by ZaleYu** [comment]
Hi burrbull:
This issue has been fixed, as follows.
https://github.com/OpenNuvoton/OpenOCD-Nuvoton/commit/7476a3cee7a2498fa7cb23c0bef7cccc29b4598e

Sincerely,
Zale Yu
