### ISSUE TITLE
Port for Probe-rs

### ISSUE THREAD

**Issue by burrbull** [OpenNuvoton/OpenOCD-Nuvoton#16]
@ZaleYu I'm thinking about porting your code to Rust for https://github.com/probe-rs/probe-rs .
But `openocd` and `probe-rs` has different licenses (GPLv2 vs MIT/APACHE).
As this is other language, the code will be looked significantly different, but this is still issue.
What do you think about?

**Comment by ZaleYu** [comment]
Hi burrbull:
You can develop your Rust project based on our code. What is your concern?

Sincerely, 
Zale Yu

**Comment by burrbull** [comment]
Thanks.
