### ISSUE TITLE
Config bits read/write error?

### ISSUE THREAD

**Issue by danchouzhou** [OpenNuvoton/OpenOCD-Nuvoton#17]
Hello Zale Yu, 

I'm try to use the OpenOCD to program target board NuMaker-Volcano. I got some issue while programming config bits. 
```
# Create config bits binary file
echo -n -e "\x7F\xFB\xFF\xFD\xFF\xFF\xFF\xFF\x5A\xFF\xFF\xFF" >> config.bin
# Execute OpenOCD
sudo openocd -f /usr/local/share/openocd/scripts/interface/nulink.cfg -f /usr/local/share/openocd/scripts/target/numicroM0.cfg
```
After executing OpenOCD and connect it via ``telnet localhost 4444``, I type the following command:
```
# Erase whole chip
> numicro chip_erase
numicro chip_erase complete
# Check if config bits has been erased
> flash erase_check NuMicro.flash_config
successfully checked erase state
	Bank is erased
# Program the config bits
> flash write_bank NuMicro.flash_config config.bin 0
Nuvoton NuMicro: Flash Write ...
Have written 100%
wrote 12 bytes from file config.bin to flash bank 3 at offset 0x00000000 in 0.691948s (0.017 KiB/s)
# Check the config bits, failed in this step.
> flash verify_bank NuMicro.flash_config config.bin 0
read 12 bytes from file config.bin and flash bank 3 at offset 0x00000000 in 0.106472s (0.110 KiB/s)
contents differ
diff 0 address 0x00000000. Was 0x2e instead of 0x7f
diff 1 address 0x00000001. Was 0x00 instead of 0xfb
diff 2 address 0x00000002. Was 0x00 instead of 0xff
diff 3 address 0x00000003. Was 0x20 instead of 0xfd
diff 4 address 0x00000004. Was 0xf5 instead of 0xff
diff 5 address 0x00000005. Was 0xec instead of 0xff
diff 6 address 0x00000006. Was 0x0c instead of 0xff
diff 7 address 0x00000007. Was 0x00 instead of 0xff
diff 8 address 0x00000008. Was 0x72 instead of 0x5a
diff 9 address 0x00000009. Was 0x00 instead of 0xff
diff 10 address 0x0000000a. Was 0x00 instead of 0xff
diff 11 address 0x0000000b. Was 0x00 instead of 0xff
in procedure 'flash'
```

I'm wondering is there any things I had not noticed? Appreciate for your help.

Cheers, 
Danny

**Comment by ZaleYu** [comment]
Hi Danny:
Which target did you try?

Sincerely, 
Zale Yu

**Comment by danchouzhou** [comment]
Hello Zale Yu, 

It's M0A23EC1AC.

Cheers, 
Danny

**Comment by ZaleYu** [comment]
Hi Danny:
Could you add **-d3 -l debug_log.txt** in your commands and send me your log to debug?
Because I am going to work from home next week, M0A23EC1AC will not be on my side for at least one week.

Sincerely,
Zale Yu

**Comment by danchouzhou** [comment]
Hello Zale Yu, 

Please refer to the attached file.
[debug_log.txt](https://github.com/OpenNuvoton/OpenOCD-Nuvoton/files/7070799/debug_log.txt)

Cheers, 
Danny

**Comment by ZaleYu** [comment]
Hi Danny:
I will cope with this issue on Monday.

Thanks.

Sincerely,
Zale Yu

**Comment by ZaleYu** [comment]
Hi Danny:
To program user configuration, please use the following commands.
1. Erase config bits, using:
**numicro** **erase_isp** _address_
2. Write config bits, using:
**numicro** **write_isp** _address_ _data_
3. Read config bits, using:
**numicro** **read_isp** _address_

Sincerely,
Zale Yu

**Comment by danchouzhou** [comment]
Hello Zale Yu: 

According to your reply it works fine, thanks.
But I'm still wondering is there anythings wrong with my command?

By the way, is that possible to change the target voltage, ICP clock speed and operate Nu-Link2-Pro ISP interface (CAN, SPI, UART, etc.) by using the OpenOCD?

Cheers, 
Danny

**Comment by ZaleYu** [comment]
Hi Danny:
Your command (flash write_bank) cannot write the user configuration because it requires ISP manipulation not flash algorithm.
Regarding the target voltage changed by OpenOCD, the answer is yes. The patch will be made in the near future.

Sincerely,
Zale Yu
