### ISSUE TITLE
Can not work on Raspberry Pi 

### ISSUE THREAD

**Issue by will127534** [OpenNuvoton/OpenOCD-Nuvoton#2]
Try to use Raspberry Pi GPIO as SWD debugger, the compile is fine, and it seems to work.
But I can't connect to M2351

Here is the config file

source [find interface/raspberrypi2-native.cfg]
transport select swd
adapter_khz 10
source [find target/numicroM23.cfg]
init
targets
reset halt

Here is the result

Open On-Chip Debugger 0.10.0-dev-g7a28f97-dirty (2019-03-21-11:58)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
BCM2835 GPIO nums: swclk = 25, swdio = 24
BCM2835 GPIO config: srst = 18
cortex_m reset_config sysresetreq
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : SWD only mode enabled (specify tck, tms, tdi and tdo gpios to add JTAG mode)
Info : clock speed 1001 kHz
Info : SWD DPIDR 0x0bf11477
Error: Could not find MEM-AP to control the core
    TargetName         Type       Endian TapName            State
--  ------------------ ---------- ------ ------------------ ------------
 0* NuMicro.cpu        cortex_m   little NuMicro.cpu        unknown
Error: Could not find MEM-AP to control the core
Segmentation fault

It isn't working for Nuvoton MCU, is this project only designed for your NU-link debugger?

Thanks!

**Comment by ZaleYu** [comment]
Hi will127534:
We developed the Nuvoton-customized OpenOCD for Nu-Link, and did not guarantee that it worked well for other interface hardware. 

Sincerely, 
Zale Yu
