### ISSUE TITLE
OpenOCD support for Nuvoton 8051 microcontrollers

### ISSUE THREAD

**Issue by kristofmulier** [OpenNuvoton/OpenOCD-Nuvoton#23]
We currently support a range of ARM-based Nuvoton microcontrollers in Embeetle IDE (see https://embeetle.com/#supported-hardware/nuvoton).

We have a request from Nuvoton to support also a few 8051 families, more in particular:
 - MS51
 - ML51
 - ML54

When looking around in the targets folder, I do not find any of these families. Are they currently not supported in the Nuvoton OpenOCD?

**Comment by ccli0** [comment]
Hi Kristof Mulier
Nuvoton  OpenOCD does not support 8051 families currently.

**Comment by paulsykes** [comment]
https://github.com/OpenNuvoton/OpenOCD-Nuvoton/issues/32
