### ISSUE TITLE
Cannot select swd using buspirate as interface

### ISSUE THREAD

**Issue by PhilipPtz** [OpenNuvoton/OpenOCD-Nuvoton#31]
Using Buspirate as interface and adding "transport select swd" on the configuration file, openocd returns this message:
`Warn : Adapter driver 'buspirate' did not declare which transports it allows; assuming legacy JTAG-only
Info : only one transport option; autoselect 'jtag'
Error: Can't change session's transport after the initial selection was made
embedded:startup.tcl:21: Error: 
in procedure 'script' 
at file "embedded:startup.tcl", line 60
in procedure 'transport' called at file "scripts/interface/buspirate.cfg", line 9
in procedure 'ocd_bouncer' 
at file "embedded:startup.tcl", line 21
`

**Comment by ccli0** [comment]
Please use nulink.cfg as the interface for OpenOCD-Nuvoton version and other interfaces are not guaranteed to work.
