### ISSUE TITLE
Release "OpenOCD_V1.02.023r" not ready-to-use

### ISSUE THREAD

**Issue by danchouzhou** [OpenNuvoton/OpenOCD-Nuvoton#35]
Hello ccli0, 

I saw your new release, but the files comes up with only openocd.exe without script, .dll, etc. 
So the people who download the OpenOCD_Windows.zip or OpenOCD_Linux.zip are not able to use it directly.

Please take a look how I use your build. If the file an directory structure are all same for every release (such like arm-gcc), it will be great!
[Nuvoton-VScode-template](https://github.com/danchouzhou/Nuvoton-VScode-template)

：(
[OpenOCD_V1.02.023r](https://github.com/OpenNuvoton/OpenOCD-Nuvoton/releases/tag/v1.02.023r)

：)
[OpenOCD_V1.02.022r](https://github.com/OpenNuvoton/OpenOCD-Nuvoton/releases/tag/v1.02.022r)

Cheers, 
Danny

**Comment by ccli0** [comment]
Hi @danchouzhou 

I have re-uploaded v1.02.023 and new version v1.02.024.
Please take a look.

**Comment by danchouzhou** [comment]
Thanks for your help!
