### ISSUE TITLE
Fixup in the Readme

### ISSUE THREAD

**Issue by ehabhussein** [OpenNuvoton/OpenOCD-Nuvoton#4]
$ gdb-multiarch
(gdb) set architecture arm
(gdb) target extended-remote localhost:3333

or else it shall not work and openeocd will shutdown/exit

**Comment by ZaleYu** [comment]
Hi ehabhussein:
From the latest openocd repository(https://sourceforge.net/p/openocd/code/ci/master/tree/README), the README document only had the following description:

**After OpenOCD startup, connect GDB with

  (gdb) target extended-remote localhost:3333**

If you have any suggestion, please push your commit to the mainstream openocd(http://openocd.zylin.com/#/q/status:open).

Sincerely, 
Zale Yu
